name: Go Build and Compile

on:
  push:
    branches:
      - main

jobs:
  build-and-compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go environment
        uses: actions/setup-go@v2
        with:
          go-version: '1.23' # Specify the Go version you want to use

      - name: Build and compile
        run: |
          go build -o ./bin/your-executable ./cmd/your-main-package

      - name: Execute compiled binary
        run: |
          ./bin/your-executable

      - name: Commit all files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated commit after execution"
          git push origin main